### ISSUE TITLE
More detailed documentation

### ISSUE THREAD

**Issue by wolfracer** [iamdefinitelyahuman/eth-event#18]
hi, first of all, good job you have done here, im trying to fetch some events from an NFT contract on binance smart chain, basically i need to fetch when one of the NFT gets assigned or transfer, im having issues to do so, with web3 or even directly with json rpc API.

any help on how to do that?

**Comment by iamdefinitelyahuman** [comment]
Filtering might be useful for you - https://web3py.readthedocs.io/en/stable/filters.html#event-log-filters
