### ISSUE TITLE
Getting EventError when using brownie as a package. 

### ISSUE THREAD

**Issue by gulfpearl** [iamdefinitelyahuman/eth-event#9]
I can do transactions fine in the console, but when using brownie as a package in jupyter, as per the docs:

```
from brownie import *
p = project.load('my_projects/token', name="TokenProject")
p.load_config()
from brownie.project.TokenProject import *
network.connect('development')
```

I get the following error, even though the transaction goes through:

```
eth_event/main.py", line 282, in _decode
    raise EventError("Insufficient event data")
```

**Comment by iamdefinitelyahuman** [comment]
This sounds related to https://github.com/iamdefinitelyahuman/brownie/issues/511. If I'm right, there was some conversation on Gitter about it [here](https://gitter.im/eth-brownie/community?at=5eb7ce7714b48f0698bf8384) that might be useful for you.

Could you provide a bit more info?  Specifically:

* the source code for the events in the contract where this error occurs
* the raw event log data from the transaction

Thanks!

**Comment by iamdefinitelyahuman** [comment]
Fixed in https://github.com/eth-brownie/brownie/issues/511
